version: '3.8'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
  app:
    container_name: bankaccount
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database      
    volumes: 
      - ./src:/app
      - ./node_modules:/app/node_modules
      
volumes:
  mongodb: {}